apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-init
  labels:
    app: nginx
  namespace: comunidade-devops
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
  initContainers: 
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup myservice; do echo 'tentando resolver'; sleep 1; done"]
